database:
  connectionstring: host=localhost port=5432 user=postgres password=postgres dbname=passwords sslmode=disable
  provider: pg
app:
  address: 127.0.0.1
  consuladdress: 127.0.0.1:8500
  linklength: 8
  port: 4000
zap:
  level: -1
  logspath: ./logs/go.log
